Repository oyiza/OddHours, pull requests merged in 2021-05, with the labels that each got.

#9 Feature/model creation
  app/src/main/java/com/example/oddhours/data/model/JobModel.kt
  app/src/main/java/com/example/oddhours/data/model/ShiftsModel.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
Labels: enhancement

#17 code refactoring
  app/src/main/java/com/example/oddhours/data/model/JobModel.kt
  app/src/main/java/com/example/oddhours/database/DatabaseHelper.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
Labels: help wanted, refactor

#18 update gradle scripts
  app/build.gradle
  build.gradle
Labels: trivial

#19 call getJobs from JobRepository class & addJobInput flow fixed
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
Labels: refactor

#20 Popup dialog for entering shifts
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
  app/src/main/res/layout/addshift.xml
Labels: enhancement

#21 DatabaseHelper Singleton & Add Shifts
  app/src/main/java/com/example/oddhours/MainActivity.kt
  app/src/main/java/com/example/oddhours/data/model/ShiftsModel.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/DatabaseHelper.kt
  app/src/main/java/com/example/oddhours/database/TableJobs.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
  app/src/main/res/layout/addshift.xml
Labels: enhancement, refactor

#22 Feature/edit and delete jobs
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
  app/src/main/res/layout/edit_delete_job.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor

#23 edit and delete job - backend implementations
  app/build.gradle
  app/src/main/java/com/example/oddhours/MainActivity.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/TableJobs.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
  app/src/main/java/com/example/oddhours/utils/Constants.kt
  app/src/main/res/layout/edit_delete_job.xml
  app/src/main/res/layout/fragment_addjob.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor
