Repository oyiza/OddHours, pull requests merged in 2021-06, with the labels that each got.

#24 Added Shifts List UI
  app/build.gradle
  app/src/main/java/com/example/oddhours/data/model/JobInfoModel.kt
  app/src/main/java/com/example/oddhours/data/model/ShiftsListModel.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/TableJobs.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ChildAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ParentAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ShiftsFragment.kt
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/shifts_list.xml
  app/src/main/res/layout/fragment_shifts.xml
  app/src/main/res/layout/shifts_detail.xml
  app/src/main/res/layout/shifts_row.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor

#25 Removed JobInfoModel and replaced all it's references with JobModel
  app/src/main/java/com/example/oddhours/data/model/JobInfoModel.kt
  app/src/main/java/com/example/oddhours/data/model/ShiftsListModel.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/TableJobs.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ParentAdapter.kt
  app/src/main/res/navigation/mobile_navigation.xml
Labels: refactor

#26 Praise/squash TODOs
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/DatabaseHelper.kt
  app/src/main/java/com/example/oddhours/database/TableJobs.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ShiftsFragment.kt
Labels: refactor

#27 Bug/overnight shifts
  app/src/main/java/com/example/oddhours/data/model/ShiftsModel.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/DatabaseHelper.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ChildAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ParentAdapter.kt
  app/src/main/java/com/example/oddhours/utils/Constants.kt
  app/src/main/res/layout/addshift.xml
  app/src/main/res/layout/shifts_detail.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor

#28 fix shifts fragment having back button that does nothing
  app/src/main/java/com/example/oddhours/MainActivity.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ShiftsFragment.kt
Labels: bug

#29 delete accompanying shifts when deleting job
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
Labels: bug

#30 Meet/refactor id file names
  app/src/main/java/com/example/oddhours/MainActivity.kt
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
  app/src/main/java/com/example/oddhours/ui/notifications/NotificationsFragment.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ChildAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ParentAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ShiftsFragment.kt
  app/src/main/res/drawable/background_rounded_corners.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_dashboard.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_list.xml
  app/src/main/res/drawable/ic_notifications.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_add_shift.xml
  app/src/main/res/layout/dialog_edit_delete_job.xml
  app/src/main/res/layout/fragment_add_job.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/fragment_shifts.xml
  app/src/main/res/layout/item_job.xml
  app/src/main/res/layout/item_no_job.xml
  app/src/main/res/layout/item_shift_detail.xml
  app/src/main/res/layout/item_shifts.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/menu/menu_bottom.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: refactor

#31 Feature/edit delete shifts
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ChildAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ParentAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ShiftsFragment.kt
  app/src/main/res/layout/dialog_edit_delete_shift.xml
  app/src/main/res/layout/item_shift_detail.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor

#32 investigated adding custom exceptions and deemed it more work than necessary at this stage
  app/src/main/java/com/example/oddhours/ui/addjob/AddJobFragment.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ChildAdapter.kt
Labels: trivial

#33 fix calculateTotalHours to allow for shifts that are less than one hour
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
Labels: bug, refactor
