Repository oyiza/OddHours, pull requests merged in 2021-08, with the labels that each got.

#36 Issue/sortshift
  app/src/main/java/com/example/oddhours/data/model/ShiftsModel.kt
  app/src/main/java/com/example/oddhours/data/repository/JobRepository.kt
  app/src/main/java/com/example/oddhours/database/DatabaseHelper.kt
  app/src/main/java/com/example/oddhours/database/TableShifts.kt
  app/src/main/java/com/example/oddhours/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ChildAdapter.kt
  app/src/main/java/com/example/oddhours/utils/Helper.kt
Labels: enhancement

#37 add no shifts layout to display 'no shifts' message
  app/src/main/java/com/example/oddhours/ui/home/HomeFragment.kt
  app/src/main/java/com/example/oddhours/ui/shifts/ShiftsFragment.kt
  app/src/main/res/layout/item_no_shift.xml
  app/src/main/res/values/strings.xml
Labels: refactor, trivial

#38 setup github actions workflow
  .github/workflows/android_build.yml
Labels: enhancement

#42 update checkout and jdk version to v2, update java version to 11
  .github/workflows/android_build.yml
Labels: refactor, ci/cd

#41 create validate_gradle_wrapper.yml
  .github/workflows/validate_gradle_wrapper.yml
Labels: enhancement, ci/cd
